### ISSUE TITLE
Branch is created, but PR is not

### ISSUE THREAD

**Issue by FredyC** [greenkeeperio/greenkeeper#342]
For example this repo: https://github.com/BlackDice/eslint-config/branches

![image](https://cloud.githubusercontent.com/assets/1096340/20421684/d78149b2-ad65-11e6-919d-4d0d43e47c90.png)

I admit that this repo is bit special since `package.json` looks like this. Perhaps greenkeeper is silently failing there when creating PR because this is unexpected?
```
  "peerDependencies": {
    "eslint": "3"
  },
  "optionalDependencies": {
    "babel-eslint": "7",
    "eslint-plugin-babel": "3"
  },
```

**Comment by finnp** [comment]
It looks like the problem right now is that you don't have tests set up. And somehow we fail to recognise this. Therefore these branches are waiting for a status to be reported. I'll consider this a bug and we will look into this.

**Comment by FredyC** [comment]
Ah I see, yea in this case adding tests did not make sense to me. It's interesting thou that for `eslin-plugin-babel` the PR was created, but not for others.

**Comment by finnp** [comment]
@FredyC That's because this was the only update that was not covered by your version range. For updates that are not in your version range we create your pull request right away. If new versions are covered by your version ranges, we usually only create a branch to see if your tests still pass.

**Comment by FredyC** [comment]
Just found out about another branch in other project, that haven't got PR created. The tests for that branch has passed: https://travis-ci.org/BlackDice/b3-chief/builds/178032443

**Comment by travi** [comment]
@finnp I'm seeing similar behavior on several repos, as of this weekend. For example, see the list for [this repo](https://github.com/travi/travi.org-admin/branches/active). All branches are reporting statuses back (and passing).

I use exact versions and [greenkeeper-keeper](https://github.com/greenkeeper-keeper/meta) to keep up with the frequency of updates. This enables me to have more confidence that I'm using the same versions when going back in the history. Therefore, this is not a case where the update in the branch is already within the range defined in `package.json`.

Anything else that I need to check on my end? Any known issues on your end that might be causing this behavior?

**Comment by finnp** [comment]
@travi Thanks for the report. This was an issue that we fixed now. However the existing branches are not going to be handled by greenkeeper anymore. So please review these and delete or merge them accordingly. Sorry for the inconvenience!

**Comment by travi** [comment]
Thanks for getting this resolved and for everything you guys are doing to continue to improve the service. It is incredibly helpful to us!

**Comment by ohjames** [comment]
This is still happening for one of my projects. On circleci you can see the branch being created: https://circleci.com/gh/ohjames/rxjs-websockets

5 branches and yet not a single PR was created.

**Comment by FredyC** [comment]
@ohjames Perhaps try [Renovate](https://github.com/marketplace/renovate) instead? This project seems kinda abandoned and Renovate works very nicely.

**Comment by ohjames** [comment]
@FredyC if it was abandoned wouldn't it be unlikely for them to spend the resources monitoring version upgrades and creating the branches etc. ?

**Comment by ohjames** [comment]
@FredyC Tried out renovate, and it works, so switched all my projects off of greenkeeper. Thanks for the recommendation.
