### ISSUE TITLE
Greekeeper should test in-range dependencies even if the repo has a lockfile

### ISSUE THREAD

**Issue by pvdlg** [greenkeeperio/greenkeeper#506]
Having a `package-lock.json` or a `yarn.lock` at the root of a repository guarantees that `npm install` or `yarn install`, when executed at the root of the repository, will produce a consistent `node_modules`.

However those files are **not published** on NPM and are **not used when installing the dependency of a dependency**.

See [yarn-lock](https://yarnpkg.com/lang/en/docs/yarn-lock/#toc-current-package-only):

> During install Yarn will only use the top-level yarn.lock file and will ignore any yarn.lock files that exist within dependencies.

and [package-lock.json](https://docs.npmjs.com/files/package-lock.json):

> One key detail about package-lock.json is that it cannot be published, and it will be ignored if found in any place other than the toplevel package.

More details in this great article: [Avoid yarn for packages for now and fully enjoy its benefits for application development](https://medium.com/@boennemann/avoid-yarn-for-packages-and-fully-enjoy-its-benefits-for-application-development-8bdd4deb33cf).

However, `npm-shrinkwrap.json` is different as it will be included in the package published on NPM and will be used when installing a dependency. See [shrinkwrap.json](https://docs.npmjs.com/files/shrinkwrap.json):

> Unlike package-lock.json, npm-shrinkwrap.json may be included when publishing a package.

Following #426, Greenkeeper does not publish a version branch for updated dependencies if it's in range of what is specified in `package.json` and if the repository contains a lock file (`package-lock.json`, `npm-shrinkwrap.json`, `yarn.lock`). See [create-version-branch.js#L43](https://github.com/greenkeeperio/greenkeeper/blob/master/jobs/create-version-branch.js#L43)

This make sense for `npm-shrinkwrap.json` if it's included in the published package, as its presence guarantees that the updated dependency  will never be installed, therefore there is no reason to test it.
But it's not correct when there is a `package-lock.json` or a `yarn.lock` in the repository as its presence **doesn't** prevent a project that uses our module as a dependency, to install it with the new dependency and possibly break.

### Example
1/ We have a project called `my-module` configured with Greenkeeper that has a dependency to `some-npm-module`:
- The file `my-module/package.json` contains `dependencies: {"some-npm-module": "^1.0.0"}`
- The file `my-module/package-lock.json` has been created and has locked `some-npm-module` to version `1.0.0`

2/ The version `1.0.1` of `some-npm-module` is published in order to fix a bug, but unfortunately due to a mistake it creates a breaking change.

3/ Greenkeeper detects the new version and runs. Due to [this line](https://github.com/greenkeeperio/greenkeeper/blob/master/jobs/create-version-branch.js#L43),  nothing happen, no branch is created, no test is run, no PR or issue opened. This is because `1.0.1` statifies `^1.0.0` and there is a `package-lock.json`.

_As a side note, at this point, executing `npm install` at the root of `my-module` doesn't do anything as version `1.0.0` of `some-npm-module` is locked._

4/ Someone creates a new project called `new-project` and wants to use `my-module` as a dependency and type `npm install my-module --save`. NPM will install:
- `my-module` version `1.0.0`
- `some-npm-module` version `1.0.1` which contains a non detected breaking change.

This is because `my-module` specifies `^1.0.0`, so NPM installs the latest satified version. The `package-lock` in `my-module` is **not used here**, it's not even present in the published package therefore `npm install` executed in `new-project` has no way to knows it even exists.

💥 For the creator of `new-project` the `my-module` module is "broken" 💥

**It seems that currently, repositories with a `yarn.lock` or a `package-lock.json` are not tested by Greenkeeper for in-range dependency updates.**

### Solution

I think, the correct behavior of Greenkeeper should be:

|                                                                                                   | New dep satisfies range         | New dep doesn't satisfies range |
| --------------------------------------------------------------------------------------------- | ------------------------------- | ------------------------------- |
|`npm-shrinkwrap.json` present and published                                                    | Nothing                         | GK creates branch and opens PR  |
|`yarn.lock` or `package-lock.json` present or `npm-shrinkwrap.json` present and not published  | GK creates a branch to trigger CI | GK creates a branch and opens PR  |

**Comment by gr2m** [comment]
Thanks so much for taking the time to write up this issue Pierre, greatly appreciated. I’m not the lockfile expert on our team, they are all on well deserved vacation right now. But I’m eager to learn and even more eager to help you out. Also pinging @travi as he brought up a similar issue on #434.

My own understanding of [Step 2 of how `@greenkeeper/lockfile works](https://github.com/greenkeeperio/greenkeeper-lockfile) is that it should workaround this: 

> Greenkeeper detects the new version and runs. Due to [this line](https://github.com/greenkeeperio/greenkeeper/blob/master/jobs/create-version-branch.js#L43),  nothing happen, no branch is created, no test is run, no PR or issue opened. This is because `1.0.1` statifies `^1.0.0` and there is a `package-lock.json`

By running `greenkeeper-lockfile-update` before running tests it should get version `1.0.1` of the dependency and your tests should fail if they catch the accidental breaking change in the patch version update and Greenkeeper than should create an issue to let you know about it.

If that is not yet helping, maybe we could create an example repository to showcase the problem? I think that would help us to get all on the same page. 

Thanks a lot for your continuous support and patience with us (well, me, in this case :smile: )

**Comment by vanduynslagerp** [comment]
@gr2m, thanks for the quick answer!

The problem is that GreenKeeper never creates a version branch, so no CI build is ran, so `greenkeeper-lockfile` is never executed.
Even when there is a regular CI build (not triggered by greenkeeper) `greenkeeper-lockfile` wouldn't tun due to [update.js#L46](https://github.com/greenkeeperio/greenkeeper-lockfile/blob/master/update.js#L46).

The problem happens when Greenkeeper detects a new release of a dependency published on NPM and determine if it should create a version branch to trigger a CI build, so before `greenkeeper-lockfile` is involved.

The expected behavior when a new version of `some-npm-module` is published:
1. Greenkeeper creates the branch `greenkeeper/some-npm-module-1.0.1`, updates `package.json` with `some-npm-module` version `1.0.1` and push the commit.
2. The creation of the branch would trigger a CI build.
3. The CI build would execute `greenkeeper-lockfile-update` which would install `some-npm-module` version `1.0.1`, then run the tests and fails.
4. Greenkeeper detects the CI failure and opens an issue.

I could create a repository to reproduce but the reproduction steps involves publishing a new version on NPM to trigger Greenkeeper (and see that it doesn't create a branch to trigger the tests). So in order to publish to NPM you would need to have access to the associated NPM account.

You could recreate the repositories mentioned in [Avoid yarn for packages for now and fully enjoy its benefits for application development](https://medium.com/@boennemann/avoid-yarn-for-packages-and-fully-enjoy-its-benefits-for-application-development-8bdd4deb33cf) though.

I'm willing to propose a PR but so far I have troubles running the tests (A lot of Z_DATA_ERROR errors for some reasons).

**Comment by gr2m** [comment]
Thanks for the clarifications, I think I got it now and it sounds like a bug that we should address. I’ll chat to the team and keep you posted. It might take a while, folks are on vacation until September, so please be patient with us :)

**Comment by vanduynslagerp** [comment]
No worries, I use Greenkeeper for open source projects and I'm really happy it exists and it is free for OS. So no problems with being patient :)

**Comment by travi** [comment]
@gr2m thanks for the ping. i agree that this is related to my proposal in #434. as i've mentioned, i use `save-exact` to force the branch and PR to happen, but would switch to using ranges if every release that was w/in my defined range resulted in a PR (and ideally, releases outside of my range did not result in a PR).

it seems like resolving this specific issue is at least a step in that direction.

**Comment by nevir** [comment]
I'd really love to see this as well.  In my case, I actually would like to use a lockfile for a _library_, in conjunction with greenkeeper:

* The lockfile ensures a consistent experience across developers contributing to the library
* Greenkeeper lets us know when packages within the allowable semver range break things (which, more often than not stems from dev dependencies, rather than runtime dependencies)

**Comment by unional** [comment]
This behavior should be restored. The in-range updates are patches and minor releases (most of the time) and the consuming package/application should be tested against these changes.

IMO, that is the main benefit of using greenkeeper. Even more important than testing and updating the out-of-range dependencies.

**Comment by ismay** [comment]
I’m affected by this as well. I just discovered that for my libraries, which use a lockfile and greenkeeper with greenkeeper-lockfile, I’m not protected by the usual tests that greenkeeper does. Which is kind of unexpected.

Would be great if this could be addressed 👍

**Comment by espy** [comment]
Hey everyone, thanks for your detailed feedback 😻 . Our plan for now is as follows, please let me know if this makes sense for you:

If an `npm-shrinkwrap.json` exists, we do the same thing as before: bail if semver is satisfied and continue if not. For the other two types of lockfiles (`package-lock` and `yarn-lock`), we will in future check if `gk-lockfile` is found in the repo’s `dev-dependencies`, if it is, Greenkeeper will continue (and the lockfiles will get updated), if not, we bail as before and nothing happens (because without `gk-lockfile`, the CI build wouldn‘t install anything new anyway).

This would be the fix until we get native lockfile support in Greenkeeper.

Would that help?

**Comment by pvdlg** [comment]
Yes I think it's the right solution! Thanks for taking care of it!

**Comment by travi** [comment]
that would be spectacular! 

> (and the lockfiles will get updated)

this piece [is key](https://github.com/greenkeeperio/greenkeeper/issues/434) in my mind, so thanks a ton for considering the feedback.

happy to help test things out when you are ready for that type of help.

**Comment by Realtin** [comment]
PR here: https://github.com/greenkeeperio/greenkeeper/pull/579

**Comment by espy** [comment]
Hello everyone 👋  We’ve deployed this feature [as previously described](https://github.com/greenkeeperio/greenkeeper/issues/506#issuecomment-356322154) and would be very thankful if you could let us know if it does what you expect it to before we announce it publicly. 

If you want the previous behaviour for `package-lock` and `yarn-lock` (no in-range updates ever), you can opt out with the following entry in your `package.json`:

```javascript
'greenkeeper': {
  'lockfiles': {
     'outOfRangeUpdatesOnly': true
  }
}
```
Thanks for your participation so far! 💚

**Comment by Realtin** [comment]
Hey everyone, 

We have written down all about the new handling of lockfiles: [Greenkeeper Blog](https://blog.greenkeeper.io/were-changing-the-default-behaviour-for-lockfiles-ba9cb38a985a)

This issue should be solve now!

**Comment by unional** [comment]
Is there anything need to be done to re-enable this feature?

Currently, all my repositories still do not get PR for in-range updates.

**Comment by pvdlg** [comment]
This feature is not supposed to create PR for in range updates, but just create a branch and run the tests. If the tests pass the branch is deleted, if not an issue is opened.

**Comment by unional** [comment]
Oh, sure, that make sense.

**Comment by travi** [comment]
> This feature is not supposed to create PR for in range updates, but just create a branch and run the tests. If the tests pass the branch is deleted, if not an issue is opened.

thats disappointing if thats the case. i havent had a chance to change my project to ranges instead of exact versions, but i got the impression that PRs would be sent with the lockfile updates.

> (and the lockfiles will get updated)

from https://github.com/greenkeeperio/greenkeeper/issues/506#issuecomment-356322154

without PRs for the lockfile updates, applications that use a lockfile but define semver ranges instead of exact versions would still miss out of in-range fixes and security patches.

since the new behavior is configurable, allowing you to opt-out. could we consider a way to configure opt-ing into PRs for those lockfile updates?

**Comment by pvdlg** [comment]
My understanding of [comment](https://github.com/greenkeeperio/greenkeeper/issues/506#issuecomment-356322154) is that the lockfile will be updated on the CI before running the tests, so the tests are actually ran with the updated dependency. And if the test pass nothing more happens. If they don't pass an issue is opened.

> without PRs for the lockfile updates, applications that use a lockfile but define semver ranges instead of exact versions would still miss out of in-range fixes and security patches.

In order to get the last in-ranges fixes and security patches, why not disabling the lockfiles? The lockfiles avoid situation in which a new contributor clone your repo and the build break due to a new dependency with which your repo has never been tested.
But Greenkeeper guarantees that won't happen because the tests will be ran for each updates.
What benefits does lockfiles bring when you use GreenKeeper?

> since the new behavior is configurable, allowing you to opt-out. could we consider a way to configure opt-ing into PRs for those lockfile updates?

This is something different than the present issue. I guess a solution to update the lockfile periodically or on dependency update would be handled later on, per:

> This would be the fix until we get native lockfile support in Greenkeeper.

**Comment by travi** [comment]
> In order to get the last in-ranges fixes and security patches, why not disabling the lockfiles? 

both options have trade-offs. 
* with a lockfile, you don't get the latest in-range version automatically because the lockfile needs to be updated since an exact version is locked.
* without a lockfile, you do get the latest in-range version, but run the risk of having different in-range versions between developers, ci, and production. 

the second option (not using a lockfile) is a problem when a breaking change is accidentally released as a minor or patch version accidentally by a package maintainer (whether direct or in-direct dependency). since npm does not force the download of the latest in-range version if a developer already has a version installed that satisfies a range, it can get very difficult to track down what introduced the breakage. also, on hosts like heroku that dont use the packages that were installed on ci for running the test suite, it is possible that an untested version gets deployed to production if a version is released between the test step and deploy step. i're run into this too many times, even with a continuous deployment pipeline.

i would very much rather be somewhat behind than to deal with the inconsistencies across machines. through my use of greenkepeer and the rate that packages are released, packages are typically not out of date for very long (even when indirect). 

for applications (this is not important for packages since the lockfile is not used by consumers), i do not use semver ranges, so that it forces greenkeeper to send me a PR when a direct dependency publishes a new version. if greenkeeper were to start sending PRs for the lockfile updates at some point, i could stop using exact versions and start using semver ranges for applications.

> This is something different than the present issue. I guess a solution to update the lockfile periodically or on dependency update would be handled later on, per:
>
>>This would be the fix until we get native lockfile support in Greenkeeper.

that's fair. would love to see that happen at that point, but i definitely misunderstood how far this change would go. on the plus side, this does allow me to open up exact versions to instead use semver ranges for packages (still not applications though)
